<?php

namespace App\Services\Spotify;

use App\Models\Setting;
use App\Models\Track;
use Illuminate\Support\Carbon;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Log;
use SpotifyWebAPI\SpotifyWebAPIException;

class SpotifyPlaylistService
{
    public function __construct(protected SpotifyService $spotifyService) {}

    /**
     * @return array{playlist_id: string, playlist_url: string, track_count: int, name: string}
     */
    public function createTopTracksPlaylist(string $timeRange = 'long_term'): array
    {
        $api = $this->spotifyService->getAuthenticatedApi();

        if (! $api) {
            throw new \Exception('Spotify not connected');
        }

        try {
            $topTracks = $api->getMyTop('tracks', [
                'limit' => 50,
                'time_range' => $timeRange,
            ]);

            if (empty($topTracks->items)) {
                throw new \Exception('No top tracks found for the selected time range.');
            }

            $spotifyUserId = Setting::get('spotify_id');

            if (! $spotifyUserId) {
                $me = $api->me();
                $spotifyUserId = $me->id;
            }

            $playlistName = $this->resolvePlaylistName($timeRange);

            $playlist = $api->createPlaylist($spotifyUserId, [
                'name' => $playlistName,
                'description' => 'Your top '.count($topTracks->items).' most played tracks on Spotify, generated by Aura on '.Carbon::now()->format('d M Y').'.',
                'public' => false,
            ]);

            $trackUris = array_map(fn ($track) => $track->uri, $topTracks->items);

            $api->addPlaylistTracks($playlist->id, $trackUris);

            Log::info("Created Spotify playlist '{$playlistName}' with ".count($trackUris).' tracks');

            return [
                'playlist_id' => $playlist->id,
                'playlist_url' => $playlist->external_urls->spotify,
                'track_count' => count($trackUris),
                'name' => $playlistName,
            ];
        } catch (SpotifyWebAPIException $e) {
            Log::error('Spotify API error creating playlist: '.$e->getMessage());
            throw new \Exception('Failed to create playlist: '.$e->getMessage());
        }
    }

    /**
     * @return array{playlist_id: string, playlist_url: string, track_count: int, name: string}
     */
    public function createDateRangePlaylist(Carbon $startDate, Carbon $endDate): array
    {
        $api = $this->spotifyService->getAuthenticatedApi();

        if (! $api) {
            throw new \Exception('Spotify not connected');
        }

        $topTracks = Track::query()
            ->join('plays', 'tracks.id', '=', 'plays.track_id')
            ->whereBetween('plays.played_at', [$startDate->startOfDay(), $endDate->endOfDay()])
            ->whereNotNull('tracks.spotify_uri')
            ->groupBy('tracks.id', 'tracks.spotify_uri')
            ->orderByRaw('COUNT(*) DESC')
            ->limit(50)
            ->select('tracks.spotify_uri', DB::raw('COUNT(*) as play_count'))
            ->get();

        if ($topTracks->isEmpty()) {
            throw new \Exception('No plays found in your local history for this period. Try syncing your tracks first.');
        }

        try {
            $spotifyUserId = Setting::get('spotify_id');

            if (! $spotifyUserId) {
                $me = $api->me();
                $spotifyUserId = $me->id;
            }

            $playlistName = 'My Top '.$topTracks->count().' — '.$startDate->format('d M Y').' – '.$endDate->format('d M Y');

            $playlist = $api->createPlaylist($spotifyUserId, [
                'name' => $playlistName,
                'description' => 'Your top '.$topTracks->count().' most played tracks between '.$startDate->format('d M Y').' and '.$endDate->format('d M Y').', generated by Aura.',
                'public' => false,
            ]);

            $trackUris = $topTracks->pluck('spotify_uri')->all();

            $api->addPlaylistTracks($playlist->id, $trackUris);

            Log::info("Created Spotify playlist '{$playlistName}' with ".$topTracks->count().' tracks');

            return [
                'playlist_id' => $playlist->id,
                'playlist_url' => $playlist->external_urls->spotify,
                'track_count' => $topTracks->count(),
                'name' => $playlistName,
            ];
        } catch (SpotifyWebAPIException $e) {
            Log::error('Spotify API error creating date range playlist: '.$e->getMessage());
            throw new \Exception('Failed to create playlist: '.$e->getMessage());
        }
    }

    private function resolvePlaylistName(string $timeRange): string
    {
        return match ($timeRange) {
            'short_term' => 'My Top 50 — Last 4 Weeks',
            'medium_term' => 'My Top 50 — Last 6 Months',
            default => 'My Top 50 — All Time',
        };
    }
}
